### PR TITLE
Add JSHint and code style checking

### PR DESCRIPTION
**Pull request by yakovkhalinsky**
Setup JSHint to help with code styling.

Initial refactor includes
- Fixing JSHint errors
- Reformatting of indentation spaces
- Adding Grunt task to check code against .jshintrc

### CODE REVIEW

**Comment by yakovkhalinsky** [comment]
@herenow I've updated the spacing, so hopefully with the new .jshintfile and .editorconfig we won't have this many files in the next diff.

Let me know if you want more or less things enforce in the .jshintrc.

Also wondering about including the Grunt task in the Travis CI build, once we get it working again :+1:

**Comment by herenow** [comment]
I’m home, i’m getting my vim ready :)

Drakov seems great, it’s not yet ready to be used as a mocked http server, right?

Jshint related I actually prefer 4 spaces, although when I wrote crate-connect it seems I was using tabs…

I don’t really care if we use 2 spaces or 4 spaces, if you prefer 2 spaces we can use it.

I’m writing some unit tests and documenting the src code atm, at a separate branch.

**Comment by yakovkhalinsky** [comment]
I'm happier with 4 spaces. I just incorrectly assumed 2 :+1: I'll update it to 4.

With Drakov, I thought it migth be a simple way of getting a fake HTTP request/response setup for unit testing actual HTTP interactions. I'm not too fussed which way we go.

Otherwise, I'm keen to get this initial PR in so I can start doing some meatier updates :smile:

**Comment by yakovkhalinsky** [comment]
OK, I think for initial style and liniting this is a pretty good setup for now.

Apparently JSHint has removed checking of spaces in tabs, which kind of suchs, but I may look at something like ESLint for better style checking in the future.

@herenow let me know if you're happy to merge this :+1:

**Comment by herenow** [comment]
You can merge it.

**Comment by yakovkhalinsky** [comment]
Merging

**Pull request merged**
